Repository best-for-beast/app.bestforbeast.com, pull requests merged in 2020-11, with the labels that each got.

#14 #4 🛠 Initialize project boilerplate. Use Svelte, Typescript, Rollup, Tailwind CSS
  .eslintignore
  .eslintrc.json
  .gitignore
  .prettierrc.json
  README.md
  package-lock.json
  package.json
  public/favicon.png
  public/global.css
  public/index.html
  rollup.config.js
  src/App.svelte
  src/components/layout/Footer.svelte
  src/components/layout/Header.svelte
  src/components/layout/Hero.svelte
  src/components/layout/index.ts
  src/components/utility/TailwindProvider.svelte
  src/components/utility/index.ts
  src/main.ts
  tailwind.config.js
  tsconfig.json
Labels: nfr

#16 #5 Review - "Add pet" moved to dashboard, EmptyDashboardState deleted, removed unnecessary nav.
  src/components/layout/Header.svelte
  src/routes/Router.svelte
  src/routes/dashboard/DashboardEmpty.svelte
  src/routes/dashboard/index.ts
  src/routes/dashboard/pet-list/PetList.svelte
  src/routes/dashboard/pet-list/PetListAddItem.svelte
  src/routes/dashboard/pet-list/PetListItem.svelte
  src/routes/dashboard/pet-list/index.ts
  src/services/api/api-client.ts
  src/services/api/pets/interfaces.ts
Labels: review

#15 #5 ✨ Show the list of pets
  .eslintignore
  .eslintrc.js
  .eslintrc.json
  .nvmrc
  .prettierignore
  .vscode/settings.json
  jest.config.js
  package-lock.json
  package.json
  patches/eslint-plugin-svelte3+2.7.3.patch
  patches/prettier+2.1.2.patch
  public/mockServiceWorker.js
  rollup.config.js
  src/App.svelte
  src/assets/svg/arrow-circle-right.svg
  src/assets/svg/dog-and-cat.svg
  src/assets/svg/female.svg
  src/assets/svg/male.svg
  src/components/layout/Container.svelte
  src/components/layout/Header.svelte
  src/components/layout/Hero.svelte
  src/components/layout/Layout.svelte
  src/components/layout/index.ts
  src/main.ts
  src/mocks/browser.ts
  src/mocks/data/pets.ts
  src/mocks/handlers.ts
  src/routes/Router.svelte
  src/routes/dashboard/Dashboard.svelte
  src/routes/dashboard/index.ts
  src/routes/dashboard/pet-list/PetGender.svelte
  src/routes/dashboard/pet-list/PetList.svelte
  src/routes/dashboard/pet-list/PetListAddItem.svelte
  src/routes/dashboard/pet-list/PetListItem.svelte
  src/routes/dashboard/pet-list/helpers.spec.ts
  src/routes/dashboard/pet-list/helpers.ts
  src/routes/dashboard/pet-list/index.ts
  src/routes/index.ts
  src/routes/not-found/NotFound.svelte
  src/routes/not-found/index.ts
  src/services/api/api-client.ts
  src/services/api/pets/index.ts
  src/services/api/pets/interfaces.ts
  src/services/api/pets/pets.ts
  src/types/svg.d.ts
  svelte.config.js
  tsconfig.json
Labels: enhancement, nfr

#17 #6 ✨ As a Pet Owner I want to easily add a new pet of mine so I can see it among rest of my pets.
  .github/workflows/tests-and-code-analysis.yml
  .github/workflows/tests.yml
  .gitignore
  README.md
  jest.config.js
  jest/setup-tests.ts
  jest/svg-transform.js
  package-lock.json
  package.json
  sonar-project.properties
  src/assets/svg/dog-and-cat.svg
  src/assets/svg/file-upload.svg
  src/main.ts
  src/mocks/browser-worker.ts
  src/mocks/data/pets.ts
  src/mocks/handlers.ts
  src/mocks/node-worker.ts
  src/routes/dashboard/pet-list/AddPetCard.svelte
  src/routes/dashboard/pet-list/CreatePetForm.svelte
  src/routes/dashboard/pet-list/PetGender.svelte
  src/routes/dashboard/pet-list/PetList.svelte
  src/routes/dashboard/pet-list/PetListItem.svelte
  src/routes/dashboard/pet-list/helpers.spec.ts
  src/services/api/api-client.ts
  src/services/api/pets/contracts.ts
  src/services/api/pets/interfaces.ts
  src/services/api/pets/pets.ts
  src/tests-identifiers.ts
  src/tests/pet-adding.spec.ts
  src/tests/pet-browsing.spec.ts
  tsconfig.json
Labels: enhancement
